---
- hosts: all
  become: true
  vars:
    hostname: "dev"
    dbuser: "root"
    dbpasswd: "password"
    databases: []
    sites: []
    php_version: "7.4"
    php_modules: ['php{{ php_version }}-mysql', 'php{{ php_version }}-gd', 'php-apcu', 'php{{ php_version }}-curl', 'php{{ php_version }}-intl', 'php-memcached', 'php{{ php_version }}-mbstring', 'php{{ php_version }}-xml', 'php{{ php_version }}-pgsql', 'php{{ php_version }}-dev']
    install_db: "no"
    install_nginx: "no"
    install_php: "no"
    install_beanstalkd: "no"
    install_redis: "no"
    install_javascript_build_system: "no"
    node_major_version: "13"
    install_gems: []
    php_configs: []
    install_postgresql: "no"
    postgresql_version: "11"
    postgresql_user: "root"
    postgresql_passwd: "password"
    postgresql_databases: []
    enable_swap: "yes"
    swap_size_in_mb: 1024
    install_rabbit_mq: "no"
    install_smenu: "no"
    boost_pam_limits: "no"
    boosted_pam_limit: "40000"
  tasks:
    - import_tasks: tasks/system.yml
    - import_tasks: tasks/swap.yml
      when: enable_swap == "yes"
    - import_tasks: tasks/terminal.yml
    - import_tasks: tasks/redis.yml
      when: install_redis == "yes"
    - import_tasks: tasks/mysql.yml
      when: install_db == "yes"
    - import_tasks: tasks/nginx.yml
      when: install_nginx == "yes"
    - import_tasks: tasks/php.yml
      when: install_php == "yes"
    - import_tasks: tasks/php-fpm.yml
      when: install_php == "yes"
    - import_tasks: tasks/beanstalkd.yml
      when: install_beanstalkd == "yes"
    - import_tasks: tasks/nodejs.yml
      when: install_javascript_build_system == "yes"
    - import_tasks: tasks/ruby.yml
    - import_tasks: tasks/postgresql.yml
      when: install_postgresql == "yes"
    - import_tasks: tasks/rabbitmq.yml
      when: install_rabbit_mq == "yes"
    - import_tasks: tasks/smenu.yml
      when: install_smenu == "yes"
    - import_tasks: tasks/python.yml
  handlers:
    - name: restart php-fpm
      service: name=php{{ php_version }}-fpm state=restarted
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart redis
      service: name=redis state=restarted
    - name: restart mysql
      service: name=mysql state=restarted
